import "../index.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import clsx from "clsx";
import { fontSans } from "../config/fonts";
// import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "RisetFT",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("font-sans antialiased", fontSans.className)}>
        {children}
      </body>
    </html>
  );
}
